---
# Source: nodejsapp/templates/nodejs-svc.yaml
apiVersion: apps/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app:nodejsapp
  name: nodejsapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodejsapp
  type: LoadBalancer
status:
  loadBalancer: {}
---
# Source: nodejsapp/templates/nodejsapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nodejsapp
  labels:
    app: nodejsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
      - name: nodejsapp
        image: abhizeet/nodenew
        ports:
        - containerPort: 80
