apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ include "nodejsapp.name" . }}
  name: {{ include "nodejsapp.name" . }}-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{  include "nodejsapp.name" . }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
